// Menu action types
export const MENU_LIST_REQUEST = 'MENU_LIST_REQUEST';
export const MENU_LIST_SUCCESS = 'MENU_LIST_SUCCESS';
export const MENU_LIST_FAILURE = 'MENU_LIST_FAILURE';

export const MENU_CREATE_REQUEST = 'MENU_CREATE_REQUEST';
export const MENU_CREATE_SUCCESS = 'MENU_CREATE_SUCCESS';
export const MENU_CREATE_FAILURE = 'MENU_CREATE_FAILURE';

export const MENU_UPDATE_REQUEST = 'MENU_UPDATE_REQUEST';
export const MENU_UPDATE_SUCCESS = 'MENU_UPDATE_SUCCESS';
export const MENU_UPDATE_FAILURE = 'MENU_UPDATE_FAILURE';

export const MENU_DELETE_REQUEST = 'MENU_DELETE_REQUEST';
export const MENU_DELETE_SUCCESS = 'MENU_DELETE_SUCCESS';
export const MENU_DELETE_FAILURE = 'MENU_DELETE_FAILURE';
